### PR TITLE
Selectable Field

### PR DESCRIPTION
**Pull request by tinenhao**
image

### CODE REVIEW

**Comment by tinenhao** [comment]
[Selectable field](https://trello.com/c/xJ6Vsfuo/20-selectable-field)

**Comment by cjunxiang** [comment]
PR names should describe what you're doing. 

"Implement Selectable Field in XX Screen"

**Comment by cjunxiang** [comment]
LGTM but get someone else clearer of the task to approve i guess :')

**Review by hui444 — APPROVED** [review]
lgtm!

**Pull request merged**
