### PR TITLE
Gym History API bug fix

### PR DESCRIPTION
**Pull request by vinatsx**

### CODE REVIEW

**Comment by vinatsx** [comment]
[Backend Bugfix - History API unix date returned not accurate](https://trello.com/c/cQLKETGZ/33-backend-bugfix-history-api-unix-date-returned-not-accurate)

**Comment by vinatsx** [comment]
[History API - sort entries in descending order](https://trello.com/c/UCDlQj40/31-history-api-sort-entries-in-descending-order)

**Comment by vinatsx** [comment]
[Key With Me Page - APIs on Key With Me Page to do a check, prevent users from doing POST request if they're not allowed to](https://trello.com/c/mJtPvuDF/37-key-with-me-page-apis-on-key-with-me-page-to-do-a-check-prevent-users-from-doing-post-request-if-theyre-not-allowed-to)

**Review by angnobel — APPROVED** [review]
LGTM

**Pull request merged**
